### ISSUE TITLE
Update milestones

### ISSUE THREAD

**Issue by brobeson** [brobeson/ActionRelease#3]
### Version

1.0.1

### New step

```text
if "Next Version" milestone exists:
  if "Next Version" milestone has open issues:
    report error - all issues must be closed
  else if "Next Version" milestone has closed issues:
    rename "Next Version" milestone to "vA.B.C"
    close "vA.B.C" milestone
    create new "Next Version milestone
```

### Tasks

- [ ] Check if a milestone already exists for the new version.
- [ ] Check if a "Next Release" milestone exists.
- [ ] Get a list of open issues in the "Next Release" milestone.
- [ ] Modify "Next Release" milestone:
- [ ] Change the title
- [ ] Change the description
- [ ] Change the release data
- [ ] Change the status
- [ ] Create the new milestone
- [ ] Move open issues from the old milestone to the new milestone

**Comment by brobeson** [comment]
```mermaid
flowchart
getVersionMilestone[Get version milestone]
--> getNextMilestone[Get next release milestone]
--> versionExists{Version milestone exists?}
-- yes --> nextExists{Next milestone exists?}
  -- yes --> moveIssues[Move open issues from version to next]
  nextExists-- no --> ejectIssues[Move open issues to no milestone]
versionExists-- no -->createVersion[Create version milestone]
--> moveIssuesToVersion[Move closed issues to version milestone]
--> closeVersion[Close version milestone]
ejectIssues --> closeVersion
moveIssues --> closeVersion
```
